### ISSUE TITLE
Cannot delete theme in production

### ISSUE THREAD

**Issue by johannesdwicahyo** [vinsol-spree-contrib/spree_themes#15]
I can't delete uploaded themes in production env

`Errno::ENOENT: No such file or directory @ unlink_internal - /`

any help?

**Comment by PareshGupta** [comment]
Hi @johannesdwicahyo ,
There was an issue when deleting the theme raises exception. This was because it could not find the theme directory in the Themes path under file structure.

The issue has been fixed in the PR https://github.com/vinsol-spree-contrib/spree_themes/pull/16 and merged.

Let us know if you face any other issue.
